branches:
  only: src
language: python
python: '2.7'
sudo: false
cache: pip
before_script: gem install sass
script: pelican -s publishconf.py
after_success: "./generate.sh deploy"
env:
  global:
    secure: S0h1ZR7Ku3Hhgel7bIYf5jiwA3DsWvebTR6DHkvO/pJaYRrfW/IIPO6gxHQziFDfupOYEqMW+ikxtMOjF3Cz6h2DtKU9qpPMhZzN7L8//CiIeRHO1QjIZoTw+wrVZJi6GMrmJblH9myvRUttB4WVEDqdgtQaJuHiqzMgFFCZS3NueXAmjWSr+fplNwYqDWjFOFKsFn7SDA0DL5x1gTzu5ynRQGm7CNGul2F2NVcSMoO6nt3amXE6fAZfd/ZuuThhPM1/rSzM8gIOiGE96TYFgLB8rcK7GSpVRihJBTzG5SRhTaxnas3iou5UXakVwMn/qOGjFXElAfA7PdWJj+2ngvLzSaAxaqeKZ8db8qzd319HBvE5rBBgRugnVhDmo9L1enmZE/ywbnz0tmwcMvhRO4kMuDP2ihJ+UYuHejGVipmHwYiaA+2q1GR6moGE5AJeQfud7Ug5H82b0xtgEAJICwwyP1hXvf4NtZUcuj4zY2rsrDbDCFgpF56J7uTTylPYy+d2lLx3sQ42wgwA10kCqS+JwWqPYNlu/He9F/vWF+/GCIAHPVgmj3E1scSTDugnikm3l78gt3auISuAGarvxm61r6Ns/W6CHz5Kg1YhgPujlsqOL4ZkXRO6at+vpMgwJmH0YYy6BZkzGnzb6Ous48dQy+F09ncVQYeFCokiHyo=
